env: test
app_name: fizzy-disk
log_level: 5
log_path: logger/
listen_address: 50009
public_key_path: config/public.key
private_key_path: config/private.key
root_path_name: fizzy-netdisk

# 主服务器设置
remote_conf: 
  #例ip:  http://127.0.0.1:8080
  ip: http://localhost
  group: fizzy

local_conf:
  # 空间存储位置
  local_path: ./fizzy-netdisk/
  # 单位Byte: 总容量 5GB
  total_space: 5368709120